name: Main
on:
  push:
    branches: 
      - main
  pull_request:
  workflow_dispatch:
    inputs:
      job_name:
        type: choice
        description: 'Job to be run'
        default: commerce
        required: true
        options:
        - commerce
        - cinnamon
      environment:
        type: choice
        description: Select the environment
        default: QA
        options:
        - QA
        - DEV
        - PROD
jobs:
  
  commerce:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    name: Commerce
    steps:
        - if: github.event.inputs.job_name == 'commerce'
        - run: echo $(date +%Y)
        - run: echo ${{ github.ref }}
        - run: echo ${{  env.ENVIRONMENT }}
          env:
            ENVIRONMENT: ${{ github.event.inputs.environment }}
        
        - if: github.event.inputs.job_name == ' '
        - run: echo $(date +%Y)
        - run: echo ${{ github.ref }}
        - run: echo ${{  env.ENVIRONMENT }}
          env:
            ENVIRONMENT: QA
  cinnamon:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    name: Cinnamon
    steps:
        - if: github.event.inputs.job_name == 'cinnamon'
        - run: echo $(date +%Y)
        - run: echo ${{ github.ref }}
        - run: echo ${{  env.ENVIRONMENT }}
          env:
            ENVIRONMENT: ${{ github.event.inputs.environment }}
        - if: github.event.inputs.job_name == ' '
        - run: echo $(date +%Y)
        - run: echo ${{ github.ref }}
        - run: echo ${{  env.ENVIRONMENT }}
          env:
            ENVIRONMENT: QA
